#!/usr/bin/env ruby
require "reversepoddependency"

podSource = Reversepoddependency::SepcAnalyse.new(ARGV[0],ARGV[1])
resultHash = podSource.getAnalyseResult

puts "all Main Pods ,not contain Subspec"
puts "-----------------------------------"
resultHash.each {|key,value|
	puts key
}
puts "\n"
puts "all pods ,contain Subspec"
puts "-----------------------------------"
resultHash.each {|key,value|
	puts "#{key}->"
	puts value
	puts '---'
}